server:
  port: 8080

spring:
  application:
    name: transfer-gateway
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

account-twin-service:
  url: http://localhost:8081