server:
  port: 8080

spring:
  application:
    name: transfer-gateway
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  jackson:
    serialization:
      write-dates-as-timestamps: true

account-twin-service:
  url: http://localhost:8081
