server:
  port: 8082

spring:
  application:
    name: transfer-classifier
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  jackson:
    serialization:
      write-dates-as-timestamps: true
